### ISSUE TITLE
UWP crash while deleting SuperpoweredAdvancedAudioPlayer

### ISSUE THREAD

**Issue by Decimation23** [superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform#570] opened 2019-02-26 16:21 UTC
It appears there is a bug with deleting the SuperpoweredAdvancedAudioPlayer in the latest update (1.3.0). If I modify the C++ SuperpoweredPlayer example project in the following way, it will crash if run with no debugger attached:

`player = new SuperpoweredAdvancedAudioPlayer(NULL, playerCallback, lastSamplerate, 0);`
`delete player;`
`player = new SuperpoweredAdvancedAudioPlayer(NULL, playerCallback, lastSamplerate, 0);`
`player->open(path);`

If you just run out of the debugger, no exceptions are thrown and no errors occur. The problem only occurs if the application is run outside the IDE without a debugger attached. I should mention that I'm testing a x64 build, and the error happens in both debug and release.

**Comment by gaborszanto** [comment] 2019-02-27 14:21
This code is just wrong. Creating a player and immediately deleting it doesn't make sense.
Sure, i can reproduce this, but i can't debug this without a debugger attached. But it works good with the debugger attached. So what should i do?

**Comment by gaborszanto** [comment] 2019-02-27 14:22
I will blindly do some modifications in the destructor and hope that it will resolve this impossible thing.

**Comment by gaborszanto** [comment] 2019-02-27 14:42
Or maybe UWP applications need to be "exported" to use them standalone?

**Comment by Decimation23** [comment] 2019-02-27 15:54
The code was just demonstrating how to cause the problem. If a SuperpoweredAdvancedAudioPlayer is deleted at any point at time anywhere in the code, this error will occur in UWP. That is a real problem that can't be ignored because I'm currently deleting players at various points to clean up memory. This error did not occur in the previous version (1.2.3), so you should hopefully be able to look at the delta between the two versions to figure out what changed that might be related to this. As for why I'm deleting players, I had problems where if I have a player and I loaded a file, then loaded another file shortly after before the first load finished (i.e. the user has switched tracks extremely quickly), it would cause serious problems so now I delete the previous player and create a new one to load the second file in. That approach seems to work just fine.

**Comment by gaborszanto** [comment] 2019-02-27 17:14
A diff is not helpful because the player was not changed. However i just discovered that no modification is needed to crash the SuperpoweredPlayer example, only a player->open is required, so it's not the destructor. It only happens when running without the IDE.

**Comment by Decimation23** [comment] 2019-02-27 18:13
Is it possible it's an issue with the static library files then? What minimum SDK and target SDK versions did you specify for them?

**Comment by gaborszanto** [comment] 2019-02-27 18:43
I found the bug. When the SDK tries to set the name of any internal threads, Windows throws a (non-error, but informative) exception. And that crashes the UWP app, although such "informative" exceptions are not errors...
Will be fixed in the next update, coming in March.

**Closed by gaborszanto** 2019-02-27 18:43 UTC
