### ISSUE TITLE
Corrupted recording on some Android 10 devices

### ISSUE THREAD

**Issue by Ufosek** [superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform#620] opened 2020-05-01 14:04 UTC
Hi,

During tests of our recording module I noticed that on some devices with Android 10 recorded Audio is corrupted (see attached recordings). I also noticed similar behavior on LG G6 with Android 9 but it’s not deterministic (sometime it’s ok, sometimes it is not) so maybe it’s just something else. 
These are the results for few devices:
```
Samsung Galaxy S8 (Android 8): Ok,
Xiaomi Mi 9 (Android 10): Ok
OnePlus 7 Pro (Android 10): Corrupted
Samsung Galaxy S20 (Android 10): Corrupted
```

It looks like it happens only when recording without headphones. In our tests recording was working simultaneously with playback (you can hear music that was recorded in testing files). Recording module is almost the same as in samples. Sample Rate and Buffer Size are properly loaded from AudioManager.

I though that there may be a bug in my code but when testing it on Smule Karaoke app (!) - recorder file was corrupted in the same way (also attached).

[recordings.zip](https://github.com/superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform/files/4564556/recordings.zip)

Regards

**Comment by gaborszanto** [comment] 2020-05-03 12:08
Can you reproduce the same problem with the recorder example project in the latest version of the Superpowered SDK?

**Comment by Ufosek** [comment] 2020-05-04 10:49
@gaborszanto It is exactly the same. I attach recording from S20. I used sample project with ver 2.0.5
[recording_s20.wav.zip](https://github.com/superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform/files/4574142/recording_s20.wav.zip)

**Comment by gaborszanto** [comment] 2020-05-04 11:21
Are you sure it links to the latest version of Superpowered, so no parts from any old version (such as SuperpoweredAndroidAudioIO.cpp) were used?

**Comment by Ufosek** [comment] 2020-05-04 11:34
@gaborszanto Today I downloaded latest SP SDK, opened Examples_Android -> SuperpoweredRecorder and run the project. Since this example uses SDK from the same downloaded folder I am sure it is the latest version. Maybe something is not up-to-date in examples?

**Comment by gaborszanto** [comment] 2020-05-04 11:39
The examples are up-to-date, they wouldn't run otherwise. I'm not sure how to resolve this problem, since I'm not able to reproduce it here.

**Comment by Ufosek** [comment] 2020-05-04 11:47
@gaborszanto I first thought they it may be something with this specific device (Samsung Galaxy S20) but the same happened with others (OnePlus 7 Pro). Are you able to test it on one of these devices? If it is working then maybe you would be able to send compiled apk which I could then test to eliminate in 100% errors from my "side"?

**Comment by gaborszanto** [comment] 2020-05-04 11:48
I've a Galaxy S10e and a Xiaomi Mi Mix 2S.

**Comment by gaborszanto** [comment] 2020-05-11 08:41
Can you try the following replacement for SuperpoweredAndroidAudioIO.cpp please, and let me k
[SuperpoweredAndroidAudioIO.cpp.zip](https://github.com/superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform/files/4608475/SuperpoweredAndroidAudioIO.cpp.zip)

now the result?

**Comment by Ufosek** [comment] 2020-05-11 12:53
Hey, unfortunately it looks the same. As an addition I can say that recorded audio is slowed down comparing to "original" - I attach samples with comparison.


[rec.wav.zip](https://github.com/superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform/files/4609657/rec.wav.zip)

**Comment by gaborszanto** [comment] 2020-05-11 14:23
What is the buffer size and sample rate as passed from Java to the native layer?

**Comment by Ufosek** [comment] 2020-05-11 14:30
For S20:
sampleRate: 48000
bufferSize: 192

The same is for S8.

**Comment by gaborszanto** [comment] 2020-05-12 11:07
Does it have any impact if Superpowered::CPU::setSustainedPerformanceMode is not used in the native layer?

**Comment by Ufosek** [comment] 2020-05-12 13:00
Hmmm In RecorderExample I don't see any use of `Superpowered::CPU::setSustainedPerformanceMode` (It is in SuperpoweredPlayer though).

**Comment by gaborszanto** [comment] 2020-05-13 08:11
Then I've no idea, but this isn't the first time when some Galaxy devices with some Android builds produces audio artifacts due bad scheduling of audio I/O in the system audios tack.

**Comment by gaborszanto** [comment] 2020-05-20 14:17
Another developer reported that fixing the sample rate on the S20 to 44100 works great, indicating that the resampler in the S20's audio stack is broken. Does it work if you fix sample rate to 44100 and buffer size to 192 on the S20?

**Comment by Ufosek** [comment] 2020-05-22 14:10
@gaborszanto Yes I can confirm that setting 44100 fixed the issue! I am wondering how to apply it - hard-coding this value (44100) for all devices does not seem to be the best option.

**Comment by gaborszanto** [comment] 2020-05-25 07:01
There is no way to detect this erratic behaviour currently. It's strange to see that premium devices ship with incredibly bad mistakes still.

**Comment by gaborszanto** [comment] 2020-05-27 11:52
What is returned in Java using:
AudioRecord.getMinBufferSize(48000, AudioFormat.CHANNEL_IN_MONO, AudioFormat.ENCODING_PCM_16BIT); ?

And the same with 44100?

**Comment by Ufosek** [comment] 2020-05-28 08:16
@gaborszanto These are the results I get:
```
SAMSUNG S8: for 48000=3840, for 44100=3528
SAMSUNG S20: for 48000=3840, for 44100=3528
LG G6: for 48000=3840, for 44100=3584
```

**Comment by gaborszanto** [comment] 2020-05-28 09:56
I thought we'd get some value that helps us deciding if the reported sample rate is good or bad, but I can't come up with an idea.

**Comment by gaborszanto** [comment] 2020-05-28 10:04
What if we create an AudioRecord and question its sample rate? Like this:

AudioRecord r = new AudioRecord(MediaRecorder.AudioSource.MIC, 0, 16, 2, 192*2);
r.getSampleRate(); // what is returned here?

**Comment by Ufosek** [comment] 2020-05-29 12:01
@gaborszanto On all my devices it returned 48000 (S20, S8, G6, Nexus 5X)

**Comment by gaborszanto** [comment] 2020-05-29 15:10
That is crazy. It means they forget to do something with the resampler for the native audio path, and we have no way to detect if the provided sample rate is good or bad. It happened with major phone lineups before, now it happens again. There is nothing we can do to "fix" it unfortunately.

**Comment by mslavkovski** [comment] 2020-08-19 10:02
I have trouble running the audio recording sample project but I have no issues when using the built-in mic on both Android 10 and earlier versions. The problem is when I connect a USB mic the recording.wav file is broken and only 44 bytes long (I guess that's the wav header only and no data).
Since I have major issues with android 10 using USB audio recording (with android native recording API) I tried this library and so far without success.

**Comment by gaborszanto** [comment] 2021-03-11 08:54
I close this issue since it's Android, not Superpowered.

**Closed by gaborszanto** 2021-03-11 08:54 UTC
